version: '3'

services:
    php:
        tty: true
        build: images/php
        links:
            - postgres
        depends_on:
            - postgres
        volumes:
            - ${PROJECT_ROOT}:/var/www
            - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        command: [ "bash", "-c", "composer install && vendor/bin/doctrine-migrations migrations:migrate --no-interaction --allow-no-migration && vendor/bin/doctrine orm:schema-tool:update --force"]
#        command: [ "bash", "-c", "composer install && vendor/bin/doctrine orm:schema-tool:drop --force && vendor/bin/doctrine orm:schema-tool:create"]
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            CONTAINER_UID: ${UID}

    postgres:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres:/var/lib/postgres
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
